### PR TITLE
Build for OSX

### PR DESCRIPTION
**Pull request by h-vetinari**

### CODE REVIEW

**Comment by h-vetinari** [comment]
@dirkgr
Both py38 & py39 fail on osx with:
```
=================================== FAILURES ===================================
____________ TestSqlExecutor.test_sql_accuracy_is_scored_correctly _____________

self = <tests.parsimonious_languages.executors.sql_executor_test.TestSqlExecutor object at 0x7fda13b67be0>

    def test_sql_accuracy_is_scored_correctly(self):
        sql_query_label = (
            "( SELECT airport_service . airport_code "
            "FROM airport_service "
            "WHERE airport_service . city_code IN ( "
            "SELECT city . city_code FROM city "
            "WHERE city.city_name = 'BOSTON' ) ) ;"
        )
    
        executor = SqlExecutor(self._database_file)
        postprocessed_sql_query_label = executor.postprocess_query_sqlite(sql_query_label)
        # If the predicted query and the label are the same, then we should get 1.
>       assert (
            executor.evaluate_sql_query(
                postprocessed_sql_query_label, [postprocessed_sql_query_label]
            )
            == 1
        )

tests/parsimonious_languages/executors/sql_executor_test.py:23: 

[...]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

obj = <Process name='Process-160' parent=5608 initial>
file = <_io.BytesIO object at 0x7fda15823ea0>, protocol = None

    def dump(obj, file, protocol=None):
        '''Replacement for pickle.dump() using ForkingPickler.'''
>       ForkingPickler(file, protocol).dump(obj)
E       TypeError: cannot pickle 'sqlite3.Connection' object
```

I don't think that pickling a sqlite3 connection can ever work(?), so this seems to be obscuring some other error? Any pointers?

**Comment by dirkgr** [comment]
I made a fix at https://github.com/allenai/allennlp-semparse/pull/45.

But also, -semparse isn't really under active development anymore. I put the fix in today because it was easy, but as soon as we hit a difficult problem, we might just drop it.

**Comment by h-vetinari** [comment]
Thanks! Since the upstream PR hasn't been merged (and has failing CI?), I'll wait a bit before pulling this in.

If you want to archive the package completely, we can consider that too.

**Comment by dirkgr** [comment]
PR has been merged. Do you need a proper release before pulling it into here?

**Comment by h-vetinari** [comment]
> 
> 
> PR has been merged. Do you need a proper release before pulling it into here?

It's already included in this PR. 🙃 
Just forgot to hit merge...

**Comment by dirkgr** [comment]
🎂

**Pull request merged**
